###
### This flowfile is intended to highlight best practices utilizing Liquibase Pro
### Review and update prior to use
###
### Liquibase sales: https://www.liquibase.com/contact
### Liquibase support: https://support.liquibase.com/knowledge
###

### 
### Prior to running the following files must exist in repository:
###
### 1. liquibase.flowfile.yaml
###    This flow file
###    https://docs.liquibase.com/commands/flow/flow.html
###
### 2. liquibase.checks-settings.conf
###    Liquibase quality checks configuration file
###    https://docs.liquibase.com/commands/quality-checks/home.html
###
### 3. changelog.main.xml
###    Liquibase changelog file
###    https://docs.liquibase.com/concepts/changelogs/home.html
###

###
### Global variables used in the flowfile
###
globalVariables:
  ###
  ### These variables are typically set via automation tools (see pipeline examples)
  ###
  ### Secrets
  ### These values should be pulled from a secure vault
  ###
  ### LIQUIBASE_COMMAND_URL
  ### LIQUIBASE_COMMAND_USERNAME
  ### LIQUIBASE_COMMAND_PASSWORD
  ### LIQUIBASE_LICENSE_KEY
  ###
  ### Files
  ###

###
### Stages to execute
###
stages:
  Default:
    actions:
      #
      # Restore last backup
      #
      - type: shell
        command: |
          ACCESS_TOKEN=$(curl --request POST 'https://api.neo4j.io/oauth/token' --user '${NEO4J_AURA_CLIENT_ID}:${NEO4J_AURA_CLIENT_SECRET}' --header 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'grant_type=client_credentials' | jq -r .access_token)
          curl --request POST --header "Authorization: Bearer ${ACCESS_TOKEN}" --header 'Content-Type: application/json' https://api.neo4j.io/v1/instances/${NEO4J_AURA_INSTANCE_ID}/snapshots/${NEO4J_AURA_SNAPSHOT_ID}/restore
